name: "PR Analytics"
on:
  workflow_dispatch:
    inputs:
      report_date_start:
        description: "Report date start(d/MM/yyyy)"
      report_date_end:
        description: "Report date end(d/MM/yyyy)"

permissions:
  issues: write
  contents: read
  pull-requests: read

jobs:
  create-report:
    name: "Create report"
    runs-on: ubuntu-latest
    steps:
      - name: "Run script for analytics"
        uses: AlexSim93/pull-request-analytics-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_OWNER_FOR_ISSUE: my-dudes-org
          GITHUB_REPO_FOR_ISSUE: pull-requests-analytics-playground
          GITHUB_OWNERS_REPOS: my-dudes-org/pull-requests-analytics-playground
          CORE_HOURS_START: "0:00"
          CORE_HOURS_END: "23:59"
          TIMEZONE: "Europe/London"
          REPORT_DATE_START: ${{ inputs.report_date_start }}
          REPORT_DATE_END: ${{ inputs.report_date_end }}
